version: "3.0"
services:

  build:
    image: klakegg/hugo:0.81.0
    volumes:
      - ".:/src"

  server:
    image: klakegg/hugo:0.81.0
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"

